# Generated by Django 4.2.1 on 2023-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_history_delete_caloriecalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='frgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
            ],
        ),
    ]
