# Generated by Django 4.2.1 on 2023-08-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_frgt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='frgt',
        ),
    ]
