# Generated by Django 4.2.1 on 2023-08-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_history_calculated_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='calculated_calories',
            new_name='calories_maintenance',
        ),
        migrations.AddField(
            model_name='history',
            name='calories_weight_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
