# Generated by Django 4.2.1 on 2023-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_calculated_calories_history_calories_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='calories_weight_gain',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='calories_maintenance',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='calories_weight_loss',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=8),
        ),
    ]
